"""initial migration

Revision ID: 08aa38785c1a
Revises: None
Create Date: 2016-03-05 12:22:10.513494

"""

# revision identifiers, used by Alembic.
revision = '08aa38785c1a'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'categories', ['tag'])
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'categories', type_='unique')
    ### end Alembic commands ###
